config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'pages#index'

  # API routes
  namespace :api do
    namespace :v1 do
      resources :articles
      resources :users
      post 'login', to: 'sessions#create'
      delete 'logout', to: 'sessions#destroy'
    end
  end

  # Aritcles routes
  resources :articles

  # Users routes
  resources :users, except: [:new]

  # Messages routes
  resources :messages

  # Authentication routes
  get 'about', to: 'pages#about'
  get 'signup', to: 'users#new'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  # Friends routes
  post 'addfriend', to: 'users#addfriend'
  get 'friends', to: 'users#show_friends'
  delete 'removefriend', to: 'users#removefriend'
end

app/models/message.rb
# frozen_string_literal: true

class Message < ApplicationRecord
end

app/controllers/messages_controller.rb
# frozen_string_literal: true

class MessagesController < ApplicationController
  # GET /users/new
  def new
    @message = Message.new
    @message.update(from: params[:from])
    @message.update(to: params[:to])
  end

  def create
    binding.pry
    @message = Article.new(message_params)
    if @message.save
      flash[:success] = 'Message was sent successfully'
      redirect_to friends_path
    else
      flash[:danger] = 'Message failed to send'
      redirect_to new_message_path
    end
  end

  def show; end

  def edit; end

  def index
    @messages = Message.all
    @messages = @messages.paginate(page: params[:page], per_page: 5)
  end

  def update
    binding.pry
  end

  # Never trust parameters from the scary internet, only allow the white list through.

  private

  def user_params
    params.require(:user).permit(:to, :from, :body)
  end
end

app/views/messages/_form.html.erb
Some messages

app/views/messages/edit.html.erb
<h1 align="center">Edit User Account</h1>
<%= render 'form' %>

app/views/messages/index.html.erb
<div align="center">
  <%= form_tag('/users', method: :get, class:"navbar-form navbar-center") do %>
  <%= text_field_tag :search, params[:search], class:"form-control" %>
  <%= submit_tag "Search", :name => nil, class:"mike-btn btn btn-outline-success my-2 my-sm-0" %>
  <br></br>

<% end %>
<%= will_paginate %>

<%= render 'form'%>

</div>

app/views/messages/new.html.erb
<%= render 'shared/errors', obj: @message %>
<div class="row">
  <div class="col-xs-12">
    <%= form_for(@message, :url => url_for(:controller => 'messages', :action => 'create'), :html => {class: "form-horizontal", role: "form"}) do |f| %>
    <div class="form-group">
      <div class="control-label col-sm-2">
        <%= f.label :From %>
      </div>
      <div class="col-sm-6">
        <%= f.label @message.from %>
      </div>
    </div>
    <div class="form-group">
      <div class="control-label col-sm-2">
        <%= f.label :To %>
      </div>
      <div class="col-sm-6">
        <%= f.label @message.to %>
      </div>
    </div>
    <div class="form-group">
      <div class="control-label col-sm-2">
        <%= f.label :Body %>
      </div>
      <div class="col-sm-6">
        <%= f.text_field :body, class: "form-control", placeholder: "Enter Message" %>
      </div>
    </div>
    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <%= f.submit( value: 'Send Message', class: 'btn btn-primary btn-large') %>
      </div>
    </div>
  <% end %>
</div>
</div>

app/views/messages/show.html.erb
<div class="row">
  <div class="col-md-4 col-md-offset-5 center">
    <%= gravatar_for @user, size: 150 %>
  </div>
</div>
<h3 class="mike-h3" align="center"><%= @user.username.capitalize %>'s Articles</h3>
<% if @user == current_user %>
  <%= render 'shared/user_articles', obj: @user.articles %>
<% else %>
  <%= render 'shared/user_articles', obj: @user.articles.where(:private=>false) %>
<% end %>
<div align="center">
  <%= will_paginate @user_articles %>
</div>

app/views/messages/show_friends.html.erb
<div align="center">
  <%= form_tag('/users', method: :get, class:"navbar-form navbar-center") do %>
  <%= text_field_tag :search, params[:search], class:"form-control" %>
  <%= submit_tag "Search", :name => nil, class:"mike-btn btn btn-outline-success my-2 my-sm-0" %>
  <br></br>

<% end %>
<%= will_paginate %>

<% @users.each do |user| %>
  <ul class="listing">
    <div class="row">
      <div class="well col-md-4 col-md-offset-4">
        <li><%= link_to gravatar_for(user), user_path(user) %></li>
        <li class="article-title"><%= link_to user.username, user_path(user) %></li>
        <li>
          <small><%= pluralize(user.articles.count, "article") if user.articles %></small>
        </li>
        <li>
          <%= link_to "Send Message", message_path(:from=> current_user.username, :to=>user.username), method: 'post', class: "btn btn-xs btn-primary" %>
          <%= link_to "Remove Friend", removefriend_path(:friend=> user.username), method: 'delete', class: "btn btn-xs btn-danger" %>
        </li>
      </div>
    </div>
  </ul>
<% end %>

</div>