config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'pages#index'

  # API routes
  namespace :api do
    namespace :v1 do
      resources :articles
      resources :users
      post 'login', to: 'sessions#create'
      delete 'logout', to: 'sessions#destroy'
    end
  end

  # Aritcles routes
  resources :articles

  # Users routes
  resources :users, except: [:new]

  # Messages routes
  resources :messages

  # Authentication routes
  get 'about', to: 'pages#about'
  get 'signup', to: 'users#new'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  # Friends routes
  post 'addfriend', to: 'users#addfriend'
  get 'friends', to: 'users#show_friends'
  delete 'removefriend', to: 'users#removefriend'
end

app/models/user.rb
# frozen_string_literal: true

require_relative '../../lib/sanitizing'

class User < ApplicationRecord
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i.freeze
  validates :username, presence: true, uniqueness: { case_sensitive: false }, length: { minimum: 3, maximum: 25 }
  validates :email, presence: true, uniqueness: true, format: { with: VALID_EMAIL_REGEX }
  before_save { self.email = email.downcase }

  has_many :articles

  has_secure_password

  def self.search(search)
    @users = User.all
    if search
      @word_upcase = sanitize_downcase(search)
      @word_downcase = sanitize_upcase(search)
      search_by_email.or(search_by_username)
    else
      @users
    end
  end

  def self.search_by_email
    @users.where('email LIKE ?', "%#{@word_downcase}%")
          .or(@users.where('email LIKE ?', "%#{@word_upcase}%"))
  end

  def self.search_by_username
    @users.where('username LIKE ?', "%#{@word_downcase}%")
          .or(@users.where('username LIKE ?', "%#{@word_upcase}%"))
  end

  def self.sanitize_upcase(word)
    word.split.map(&:capitalize).join(' ')
  end

  def self.sanitize_downcase(word)
    word.split.map(&:downcase).join(' ')
  end
end

app/controllers/api/v1/users_controller.rb
# frozen_string_literal: true

class Api::V1::UsersController < ApplicationController
  # GET /users/new
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Welcome to my Blog #{@user.username}. Please Login to start using it"
      redirect_to articles_path
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
    @user_articles = @user.articles.paginate(page: params[:page], per_page: 5)
  end

  def edit
    @user = User.find(params[:id])
  end

  def index
    @users = User.search(params[:search])
    render json: @users
    @users = @users.paginate(page: params[:page], per_page: 5)
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:success] = 'Your account was updated successfully'
      redirect_to articles_path
    else
      render 'edit'
    end
  end

  def addfriend
    current_user.friends.push(params[:friend])
    current_user.save
    redirect_to users_path
  end

  def removefriend
    current_user.friends.delete(params[:friend])
    current_user.save
    redirect_to friends_path
  end

  def show_friends
    @users = User.all.where(username: current_user.friends)
    @users = @users.paginate(page: params[:page], per_page: 5)
  end
  # Never trust parameters from the scary internet, only allow the white list through.

  private

  def user_params
    params.require(:user).permit(:username, :email, :password)
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  # GET /users/new
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Welcome to my Blog #{@user.username}. Please Login to start using it"
      redirect_to articles_path
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
    @user_articles = @user.articles.paginate(page: params[:page], per_page: 5)
  end

  def edit
    @user = User.find(params[:id])
  end

  def index
    @users = User.search(params[:search])
    @users = @users.paginate(page: params[:page], per_page: 5)
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:success] = 'Your account was updated successfully'
      redirect_to articles_path
    else
      render 'edit'
    end
  end

  def addfriend
    current_user.friends.push(params[:friend])
    current_user.save
    redirect_to users_path
  end

  def removefriend
    current_user.friends.delete(params[:friend])
    current_user.save
    redirect_to friends_path
  end

  def show_friends
    @users = User.all.where(username: current_user.friends)
    @users = @users.paginate(page: params[:page], per_page: 5)
  end
  # Never trust parameters from the scary internet, only allow the white list through.

  private

  def user_params
    params.require(:user).permit(:username, :email, :password, :gravatar)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= render 'shared/errors', obj: @user %>
<div class="row">
  <div class="col-xs-12">
    <%= form_for(@user, :html => {class: "form-horizontal", role: "form"}) do |f| %>
    <div class="form-group">
      <div class="control-label col-sm-2">
        <%= f.label :username %>
      </div>
      <div class="col-sm-6">
        <%= f.text_field :username, class: "form-control", placeholder: "Enter username", autofocus: true %>
      </div>
    </div>
    <div class="form-group">
      <div class="control-label col-sm-2">
        <%= f.label :email %>
      </div>
      <div class="col-sm-6">
        <%= f.text_area :email, class: "form-control", placeholder: "Enter email" %>
      </div>
    </div>
    <div class="form-group">
      <div class="control-label col-sm-2">
        <%= f.label :password %>
      </div>
      <div class="col-sm-6">
        <%= f.password_field :password, class: "form-control", placeholder: "Enter password" %>
      </div>
    </div>
    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <%= f.submit(@user.new_record? ? "Sign up" : "Update account", class: 'btn btn-primary btn-large') %>
      </div>
    </div>
  <% end %>
  <!-- <div class="col-xs-4 col-xs-offset-2"> [ <%= link_to 'Cancel request and Return to Articles Listing', articles_path %> ] </div> -->
</div>
</div>

app/views/users/index.html.erb
<div align="center">
  <%= form_tag('/users', method: :get, class:"navbar-form navbar-center") do %>
  <%= text_field_tag :search, params[:search], class:"form-control" %>
  <%= submit_tag "Search", :name => nil, class:"mike-btn btn btn-outline-success my-2 my-sm-0" %>
  <br></br>

<% end %>
<%= will_paginate %>

<% @users.each do |user| %>
  <ul class="listing">
    <div class="row">
      <div class="well col-md-4 col-md-offset-4">
        <li><%= link_to gravatar_for(user), user_path(user) %></li>
        <li class="article-title"><%= link_to user.username, user_path(user) %></li>
        <li>
          <small><%= pluralize(user.articles.count, "article") if user.articles %></small>
        </li>
        <li>
          <% unless user == current_user %>
            <% if logged_in? %>
              <% unless current_user.friends.include?(user.username) %>
                <%= link_to "Add Friend", addfriend_path(:friend=> user.username), method: 'post', class: "btn btn-xs btn-primary" %>
              <% else %>
                <button type="button" class="btn btn-xs btn-success">Friend Added
                </button>
              <% end %>
            <% end %>
          <% end  %>
        </li>
      </div>
    </div>
  </ul>
<% end %>

</div>

app/views/users/new.html.erb
<%= render 'form' %>

app/views/users/show_friends.html.erb
<div align="center">
  <%= form_tag('/users', method: :get, class:"navbar-form navbar-center") do %>
  <%= text_field_tag :search, params[:search], class:"form-control" %>
  <%= submit_tag "Search", :name => nil, class:"mike-btn btn btn-outline-success my-2 my-sm-0" %>
  <br></br>

<% end %>
<%= will_paginate %>

<% @users.each do |user| %>
  <ul class="listing">
    <div class="row">
      <div class="well col-md-4 col-md-offset-4">
        <li><%= link_to gravatar_for(user), user_path(user) %></li>
        <li class="article-title"><%= link_to user.username, user_path(user) %></li>
        <li>
          <small><%= pluralize(user.articles.count, "article") if user.articles %></small>
        </li>
        <li>
          <%= link_to "Remove Friend", removefriend_path(:friend=> user.username), method: 'delete', class: "btn btn-xs btn-danger" %>
        </li>
      </div>
    </div>
  </ul>
<% end %>

</div>