config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'pages#index'

  # API routes
  namespace :api do
    namespace :v1 do
      resources :articles
      resources :users
      post 'login', to: 'sessions#create'
      delete 'logout', to: 'sessions#destroy'
    end
  end

  # Aritcles routes
  resources :articles

  # Users routes
  resources :users, except: [:new]

  # Messages routes
  resources :messages

  # Authentication routes
  get 'about', to: 'pages#about'
  get 'signup', to: 'users#new'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  # Friends routes
  post 'addfriend', to: 'users#addfriend'
  get 'friends', to: 'users#show_friends'
  delete 'removefriend', to: 'users#removefriend'
end

app/views/layouts/_navigation.html.erb
<head>
  <meta name='viewport' content='width=device-width, initial-scale=1'>
  <link rel='stylesheet' href='https://use.fontawesome.com/releases/v5.7.0/css/all.css' integrity='sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ' crossorigin='anonymous'>
</head>

<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <i class='fas fa-book' style='margin-top: 15px; color: white; font-size:20px'></i>
      <%= link_to "MG Blog", root_path, class: "navbar-brand", id: "logo" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Articles", articles_path, class: "links" %></li>
        <li><%= link_to "Create Article", new_article_path, class: "links" %></li>
        <li><%= link_to "Users", users_path, class: "links" %></li>

      </ul>
      <%#= form_tag('/articles', method: :get, class:"navbar-form navbar-left") do %>
        <%#= text_field_tag :search, params[:search], class:"form-control" %>
          <%#= submit_tag "Search", :name => nil, class:"btn btn-outline-success my-2 my-sm-0" %>
            <%# end  %>
              <ul class="nav navbar-nav navbar-right">
                <% if logged_in? %>
                  <li><%= link_to current_user.username.capitalize+"'s Blog", user_path(current_user), class: "links" %></li>
                  <li><%= link_to "Messages", messages_path, class: "links" %></li>
                  <li><%= link_to "Friends", friends_path, class: "links" %></li>
                  <li><%= link_to "Log out", logout_path, class: "links", method: :delete %></li>
                <% else %>
                  <li><%= link_to "Log in", login_path, class: "links" %></li>
                <% end %>
                <li class="mike-signup">
                  <i class='fa fa-user' style='display: inline; color: white; font-size:15px'></i>
                  <%= link_to "Sign Up", signup_path, style: "padding-left: 1px; padding-right: 1px; display:inline", class: "links" %>
                </li>
                <!-- <li class="dropdown"> <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a> <ul class="dropdown-menu"> <li> <a href="#">Action</a> </li> <li>
                <!-- <a href="#">Another action</a> </li> <li> <a href="#">Something else here</a> </li> <li role="separator" class="divider"></li> <li> <a href="#">Separated link</a> </li> </ul> </li> -->
              </ul>
            </div>
            <!-- /.navbar-collapse -->
          </div>
          <!-- /.container-fluid -->
        </nav>

app/views/layouts/application.html.erb
<% # <%= debug(params) if Rails.env.development? %>

  <!DOCTYPE html>
  <html>
    <head>
      <title>Michael's Blog</title>
      <%= csrf_meta_tags %>
      <%= csp_meta_tag %>

      <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
      <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    </head>

    <body>
      <%= render 'layouts/navigation' %>
      <%= render 'shared/messages' %>
      <%= yield %>
    </body>
  </html>